# Used in the kernel to generate the request

services:
    Nyholm\Psr7Server\ServerRequestCreatorInterface:
        public: true
        class: Nyholm\Psr7Server\ServerRequestCreator
        arguments:
            - '@Psr\Http\Message\RequestFactoryInterface'
            - '@Psr\Http\Message\ResponseFactoryInterface'
            - '@Psr\Http\Message\ServerRequestFactoryInterface'
            - '@Psr\Http\Message\StreamFactoryInterface'
