# This file is the entry point to configure the application's services.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # Default configuration for services in *this* file
    _defaults:
        autowire: true
        public: false
        bind:
            string $environment: '%app.environment%'

    # Makes classes in src/ available to be used as services
    # This creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Kernel.php}'

    # The actions are registered separately in order to add them the "app.action" tag
    App\Action\:
        resource: '../src/Action'
        tags: ['app.action']

    # The request handler goal is to execute the middleware stack given as arguments
    # You should complete this list with your own middleware
    # !! Warning !! Order matters
    App\RequestHandler:
        public: true
        arguments:
            - '@App\Middleware\ExceptionHandler'
            - '@App\Middleware\Router'
            - '@App\Middleware\ActionHandler'

    # Inject a smaller container which contains only the actions
    App\Middleware\ActionHandler:
        arguments:
            $actionLocator: !tagged_locator app.action

    # Add more service definitions when explicit configuration is needed
    # Please note that last definitions always *replace* previous ones
